import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:3000';
type M={id:string;homeTeam:{name:string};awayTeam:{name:string};homeScore:number;awayScore:number;venue?:string;status:string;events:{minute:number;type:string;playerName?:string|null;detail?:string|null}[]};
function App(){const[matches,setMatches]=useState<M[]>([]);const[page,setPage]=useState('home');const[selected,setSelected]=useState<M|null>(null);const[online,setOnline]=useState(37);
useEffect(()=>{fetch(API+'/api/championships').then(r=>r.json()).then(x=>setMatches(x.flatMap((c:any)=>c.matches||[]))).catch(()=>{});const t=setInterval(()=>setOnline(n=>Math.max(1,n+(Math.random()>.6?1:Math.random()<.35?-1:0))),6000);return()=>clearInterval(t)},[]);
const live=selected||matches[0];
return <><header><strong>FutLiga</strong><nav><button onClick={()=>setPage('home')}>Início</button><button onClick={()=>setPage('live')}>🔴 Ao vivo</button><button onClick={()=>setPage('admin')}>⚙ Admin</button><button onClick={()=>setPage('master')}>★ Master</button></nav></header><main>
{page==='home'&&<><section className="hero"><small>FUTLIGA — PLATAFORMA DE CAMPEONATOS</small><h1>O campeonato acontecendo em tempo real.</h1><p>Resultados, eventos, escalações, torcida, premiações e patrocinadores.</p></section><div className="grid">{matches.map(m=><article className="card clickable" key={m.id} onClick={()=>{setSelected(m);setPage('live')}}><small>CAMPEONATO DE INVERNO · SEMIFINAL</small><h2>{m.homeTeam.name} <b>{m.homeScore} × {m.awayScore}</b> {m.awayTeam.name}</h2><p>🔴 {m.venue||'Campo'}</p></article>)}</div></>}
{page==='live'&&live&&<Live m={live} online={online}/>}
{page==='admin'&&<Panel title="Painel do Campeonato" items={['Campeonato','Equipes','Jogadores','Fases e rodadas','Partidas','Escalações','Partida ao vivo','Comentários e moderação','Premiações']}/>}
{page==='master'&&<Panel title="Admin Master — FutLiga" items={['Clubes','Administradores','Patrocinadores','Anúncios','Campeonatos','Histórico e arquivamento','Auditoria','Configurações']}/>}
</main></>}
function Live({m,online}:{m:M;online:number}){return <><section className="live"><small>SEMIFINAL · {m.venue||'CAMPO'}</small><h1>{m.homeTeam.name} <span>{m.homeScore} × {m.awayScore}</span> {m.awayTeam.name}</h1><div className="clock">42:07</div><b>🔴 AO VIVO — {online} pessoas assistindo</b></section><div className="grid"><section className="card"><h2>📋 Linha do tempo</h2>{m.events.map((e,i)=><div className="event" key={i}><b>{String(e.minute).padStart(2,'0')}:00</b><span>{e.type==='GOAL'?'⚽':e.type==='YELLOW'?'🟨':e.type==='RED'?'🟥':'▶️'}</span><span>{e.playerName||e.detail}</span></div>)}</section><section className="card"><h2>👥 Escalações</h2><h3>{m.homeTeam.name}</h3><p>9 · João — titular</p><p>5 · Carlos — titular</p><p>3 · Rafael — reserva</p><hr/><h3>{m.awayTeam.name}</h3><p>10 · Pedro — titular</p><p>7 · Lucas — titular</p></section></div><div className="sponsor">OFERECIMENTO · <b>KING</b><br/><small>Apoiando o futebol da nossa região.</small></div></>}
function Panel({title,items}:{title:string;items:string[]}){return <><h1>{title}</h1><div className="grid">{items.map(x=><section className="card" key={x}><h2>{x}</h2><p>Módulo da plataforma preparado para implementação e operação.</p><button>Acessar</button></section>)}</div></>}
createRoot(document.getElementById('root')!).render(<App/>);